### PR TITLE
Bugs removed.

### PR DESCRIPTION
**Pull request by qsrahman**

### CODE REVIEW

**Comment by ekelokorpi** [comment]
Can you explain this more? Works fine for me with using `this`

**Comment by qsrahman** [comment]
`cache` is a property of class `Texture` which remains the same for all instances of class `Texture`i.e `cache` is a static property.

**Comment by ekelokorpi** [comment]
For example, `fromImage` is a static method on `Texture` class, and calling `this` inside of it, is same as calling `game.Texture`.

**Comment by qsrahman** [comment]
yes bcos fromImage is a static method. see 
```
// Constructor
function Kid (name) {
    // Private
    var idol = "Paris Hilton";

    // Privileged
    this.getIdol = function () {
        return idol;
    };

    // Public
    this.name = name;
}

// Static property
Kid.town = "South Park";

// Public
Kid.prototype.getName = function () {
    return this.name;
};

Kid.prototype.getTown = function() {
    return this.town;
};

Kid.getTown2 = function() {
    return this.town;
};

 // Create a new instance

var cartman = new Kid("Cartman");

// Access private property
console.log(cartman.idol); // undefined

// Access privileged method
console.log(cartman.getIdol()); // "Paris Hilton"

// Access public property
console.log(cartman.name); // "Cartman"

// Access public method
console.log(cartman.getName()); // "Cartman"

// Assess static property with an instance
console.log(cartman.getTown()); // undefined

// Access static property on an instance
console.log(cartman.town); // undefined

// Assess static property with a static method
console.log(Kid.getTown2()); // "South Park"

// Access static property on the constructor object
console.log(Kid.town); // "South Park"
```

**Comment by ekelokorpi** [comment]
Your fix doesn't change anything.

Currently it works like this:
````javascript
var sprite = new game.Sprite('panda.png');
console.log(game.Texture.cache); // Contains instance of game.Texture for panda.png
````

And works exactly same (as it should be) after your changes.

**Comment by qsrahman** [comment]
:) you are mixing up two things i.e. class methods and instance method. Look at the code of `BaseTexture` class `remove` method, you correctly used delete game.BaseTexture.cache[this._id]. why? because delete this.cache[this._id] will not work.

**Comment by ekelokorpi** [comment]
Yes that will not work because it's instance method? `game.Texture.fromImage` is class method, and calling `this.cache` inside of it is same as calling `game.Texture.cache`.

**Pull request closed without merging**
