### PR TITLE
sound stopping by name

### PR DESCRIPTION
**Pull request by Neso**
Implemented sound stopping by name.  Didn't want to leave large
footprint in the file that why this kind of implementation.

### CODE REVIEW

**Comment by ekelokorpi** [comment]
Thanks for the PR, but always use `develop` branch. Master branch is updated only when
new version is released.

**Comment by Neso** [comment]
Would you like me to push it to develop branch or you are not interested in this?

**Comment by ekelokorpi** [comment]
I'm not really sure why i would need that function, can you give me an example?

**Comment by Neso** [comment]
Well, for me it was simple. I always know which sounds I am playing, and when I want them to stop. This would allow me to stop the sound without actually tracking its id code. That is the point.

**Comment by ekelokorpi** [comment]
Ok that makes sense. If there is multiple sounds playing from the same sound source, your code will only stop the last from the audioObjects list (and your documentation got some wrong parameters, should be name, not id). I have modified the code and added it to current develop branch. Thanks! :+1:

**Comment by Neso** [comment]
No problem, I'll be more careful next time ;) I wanted to test it but panda tool doesn't have test functionality any longer.

**Pull request closed without merging**
